config/routes.rb
Rails.application.routes.draw do

  get 'roadmap/index'

  devise_for :users
  resources :projects
  resources :rbs, :role, :requirment
  resources :pbs, :subproducts, :moduls, :components
  resources :wbs, :subtask, :workpackage
  resources :delphi, :question, :response
  resources :ram, :allocationitems
  resources :kind, controller: 'rbs'
  resources :task, controller: 'wbs'
  resources :questionaries, controller: 'delphi'
  resources :roadmaps

  root 'projects#index'

end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :modul
  has_one :allocationitem, dependent: :destroy
  validates :name, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :questionary
end

app/models/eventdate.rb
class Eventdate < ActiveRecord::Base
  belongs_to :workpackage
end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :roles, dependent: :destroy
  belongs_to :project
  validates :name, presence: true
end

app/models/modul.rb
class Modul < ActiveRecord::Base
  belongs_to :subproduct
  has_many :components, dependent: :destroy
  validates :name, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :subproducts, dependent: :destroy
  has_many :kinds, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :questionarys, dependent: :destroy
  has_many :roadmaps, dependent: :destroy
  validates :title, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionary
  belongs_to :workpackage
  has_many :responses
end

app/models/requirment.rb
class Requirment < ActiveRecord::Base
  belongs_to :role

  validates :qualifikation, :experience, presence: true
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :realistic, :optimistic, :pessimistic, presence: true, numericality: { only_integer: true }
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
  belongs_to :project
  belongs_to :questionary

  validates :start, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :kind
  has_one :allocationitem
  has_many :requirments, dependent: :destroy
  validates :name, presence: true
end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
  belongs_to :project
  has_many :moduls, dependent: :destroy
  validates :name, presence: true
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  has_many :workpackages, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subtasks, dependent: :destroy
  belongs_to :project
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :responses, dependent: :destroy
  has_many :userquests, dependent: :destroy
  has_many :questionarys, through: :userquests

  validates_presence_of :first_name, :last_name
end

app/models/userquest.rb
class Userquest < ActiveRecord::Base
  belongs_to :user
  belongs_to :questionary
end

app/controllers/delphi_controller.rb
class DelphiController < ApplicationController
  before_action :find_quest, only: [:destroy]

  def index
    @project = Project.find(params[:project])
    @newquest = Questionary.new()

  end
  def show
    @project = Project.find(params[:project])
    @questionary = Questionary.find(params[:questionary])

  end

  def create(project)
    @project = project
    last_quest_round = 0
    if @project.questionarys.last.present?
      last_quest_round = @project.questionarys.last.runde
    end
    last_quest_round = last_quest_round +1
    @quest = Questionary.new()
    @quest.runde = last_quest_round
    @quest.project_id = @project.id
    @quest.users << User.all
    respond_to do |format|
      if @quest.save
        project.tasks.each do |task|
          task.subtasks.each do |subtask|
            subtask.workpackages.each do |work|
              @question = Question.new()
              @question.workpackage_id = work.id
              @question.questionary_id = @quest.id
              @question.save
            end
          end
        end
        format.html { redirect_to delphi_index_path(project: @project), success: 'Fragebogen wurde erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @kind}
      else
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

   def destroy
    @project = @quest.project
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to delphi_index_path(project: @project), success: 'Fragebogen wurde erfolgreich entfernt.' }
      format.json { head :no_content }
    end
  end

  def new
    @project = Project.find(params[:project])
    create(@project)
  end

  private

    def find_quest
      @quest = Questionary.find(params[:id])
    end

    def quest_params
      params.require(:questionary).permit(:runde, :project_id)
    end
end

app/helpers/delphi_helper.rb
module DelphiHelper
end

app/helpers/pbs_helper.rb
module PbsHelper
end

app/helpers/ram_helper.rb
module RamHelper
end

app/helpers/rbs_helper.rb
module RbsHelper
end

app/helpers/wbs_helper.rb
module WbsHelper
end

app/views/delphi/index.html.erb
<%= render partial: '/shared/header', locals: {project: @project, linkVariable: @project, section: 'Breitband-Delphi'} %>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <%= link_to new_delphi_path(:project => @project.id) , class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--indigo-500' do %>
      <i class="material-icons">add</i>Fragebogen erzeugen
    <% end %>
    <h5> Bestehende Fragebögen </h5>
    <hr>
  </div>
  <% @project.questionarys.each do |quest| %>
      <div class="mdl-cell mdl-cell--4-col">
        <div class="question-card">
          <div class="structure mdl-card mdl-shadow--2dp">
            <div class="format mdl-card__title mdl-card--expand">
              <span class="card-title-text">Runde <%=quest.runde %></span>
            </div>
          <div class="mdl-card__actions mdl-card--border">
            <div id="tt<%= quest.id%>" class="icon material-icons">
              <%= link_to response_index_path(quest,project: @project,questionary: quest), class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored button-middle' do %>
                <i class="material-icons">folder_open</i>
              <% end %>
            </div>
             <div class="mdl-tooltip" for="tt<%= quest.id%>">
                Antworten hinzufügen
              </div>
             <div id="t<%= quest.id%>" class="icon material-icons">
                <%= link_to delphi_path(quest,project: @project,questionary: quest), class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored button-middle' do %>
                  <i class="material-icons">report</i>
                <% end %>
              </div>
              <div class="mdl-tooltip" for="t<%= quest.id%>">
                Auswerten
              </div>
              <div id="<%= quest.id%>" class="icon material-icons">
                <%= link_to delphi_path(quest), method: :delete, data: { confirm: 'Soll der Fragebogen wirklich gelöscht werden?' }, class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored button-middle' do %>
                  <i class="material-icons">delete</i>
                <% end %>
              </div>
<!--               <div class="mdl-tooltip" for="<%= quest.id%>">
                Löschen
              </div> -->
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/delphi/show.html.erb
<%= render partial: '/shared/header', locals: {project: @project, linkVariable: :back, section: 'Breitband-Delphi'} %>
<div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
  <div class="mdl-tabs__panel is-active" id="table-panel">
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp wide-table" id="test2">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">Projekt</th>
          <th class="mdl-data-table__cell--non-numeric">Arbeitspaket</th>
          <th class="mdl-data-table__cell--non-numeric">Angabe in</th>
          <th class="mdl-data-table__cell--non-numeric">Pessimistische Einschätzung</th>
          <th class="mdl-data-table__cell--non-numeric">Realistische Einschätzung</th>
          <th class="mdl-data-table__cell--non-numeric">Optimistische Einschätzung</th>
        </tr>
      </thead>
      <tbody>
          <tr class="first-level">
            <td class="mdl-data-table__cell--non-numeric"><%= @project.title %><%=@questionary.id%></td>
          </td>
            <td></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
          </tr>
          <% @questionary.questions.each do |quest| %>
            <tr class="second-level">
              <td></td>
              <td class="mdl-data-table__cell--non-numeric">
                <%=quest.workpackage.subtask.task.name%> > <%=quest.workpackage.subtask.name%> > <%=quest.workpackage.name%>
              </td>
              <td class="mdl-data-table__cell--non-numeric">Projekttagen</td>
              <td class="mdl-data-table__cell--non-numeric">Durchschnitt: <%=quest.pessimistic_average%></td>
              <td class="mdl-data-table__cell--non-numeric">
                Durchschnitt: <%=quest.realistic_average%>
              </td>
              <td class="mdl-data-table__cell--non-numeric">
                Durchschnitt: <%=quest.optimistic_average%>
              </td>
            </tr>
              <% quest.responses.each do |response| %>
              <tr class="third-level">
                <td></td>
                <td class="mdl-data-table__cell--non-numeric">
                  <%= response.user.first_name %> <%=response.user.last_name%>
                </td>
                <td class="mdl-data-table__cell--non-numeric"></td>
                <td class="mdl-data-table__cell--non-numeric"><%= response.pessimistic %></td>
                <td class="mdl-data-table__cell--non-numeric"><%= response.realistic %></td>
                <td class="mdl-data-table__cell--non-numeric"><%= response.optimistic %></td>
              </tr>
              <%end%>
          <% end %>
      </tbody>
    </table>
  </div>
</div>