config/routes.rb
Rails.application.routes.draw do

  get 'roadmap/index'

  devise_for :users
  resources :projects
  resources :rbs, :role, :requirment
  resources :pbs, :subproducts, :moduls, :components
  resources :wbs, :subtask, :workpackage
  resources :delphi, :question, :response
  resources :ram, :allocationitems
  resources :kind, controller: 'rbs'
  resources :task, controller: 'wbs'
  resources :questionaries, controller: 'delphi'
  resources :roadmaps

  root 'projects#index'

end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :modul
  has_one :allocationitem, dependent: :destroy
  validates :name, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :questionary
end

app/models/eventdate.rb
class Eventdate < ActiveRecord::Base
  belongs_to :workpackage
end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :roles, dependent: :destroy
  belongs_to :project
  validates :name, presence: true
end

app/models/modul.rb
class Modul < ActiveRecord::Base
  belongs_to :subproduct
  has_many :components, dependent: :destroy
  validates :name, presence: true
end

app/models/predecessor.rb
class Predecessor < ActiveRecord::Base
  belongs_to :workpackages
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :subproducts, dependent: :destroy
  has_many :kinds, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :questionarys, dependent: :destroy
  has_many :roadmaps, dependent: :destroy
  validates :title, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionary
  belongs_to :workpackage
  has_many :responses
end

app/models/requirment.rb
class Requirment < ActiveRecord::Base
  belongs_to :role

  validates :qualifikation, :experience, presence: true
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :realistic, :optimistic, :pessimistic, presence: true, numericality: { only_integer: true }
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
  belongs_to :project
  belongs_to :questionary

  validates :start, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :kind
  has_one :allocationitem
  has_many :requirments, dependent: :destroy
  validates :name, presence: true
end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
  belongs_to :project
  has_many :moduls, dependent: :destroy
  validates :name, presence: true
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  has_many :workpackages, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subtasks, dependent: :destroy
  belongs_to :project
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :responses, dependent: :destroy
  has_many :userquests, dependent: :destroy
  has_many :questionarys, through: :userquests

  validates_presence_of :first_name, :last_name
end

app/models/userquest.rb
class Userquest < ActiveRecord::Base
  belongs_to :user
  belongs_to :questionary
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:destroy, :show]

	def index
    @projects = Project.all
	end

  def show
    @product = Subproduct.new
  end


  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, success: 'Projekt wurde erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { redirect_to new_project_path, danger: 'Projekt nicht erstellt' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, success: 'Projekt wurde erfolgreich entfernt.' }
      format.json { head :no_content }
    end
  end

  def new
    @project = Project.new
  end

  private

    def find_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/pbs_helper.rb
module PbsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/ram_helper.rb
module RamHelper
end

app/helpers/rbs_helper.rb
module RbsHelper
end

app/helpers/wbs_helper.rb
module WbsHelper
end

app/views/projects/index.html.erb
<%= render partial: '/shared/flash_message'%>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <%= link_to new_project_path , class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--indigo-500' do %>
      <i class="material-icons">add</i> Neues Projekt
    <% end %>
    <h5> Meine Projekte </h5>
    <hr>
  </div>
  <% @projects.each do |project| %>
      <div class="mdl-cell mdl-cell--4-col">
        <div class="project-card">
          <div class="structure mdl-card mdl-shadow--2dp">
            <div class="format mdl-card__title mdl-card--expand">
              <h2 class="format mdl-card__title-text"><span class="card-title-text"><%=project.title %></span></h2>
            </div>
            <div class="mdl-card__supporting-text">
              <%= truncate(project.description, :length => 120) %>
            </div>
            <div class="mdl-card__actions mdl-card--border">
              <div id="open" class="icon material-icons">
                <%= link_to project, class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored button-middle' do %>
                  <i class="material-icons">folder_open</i>
                  <% end %>
              </div>
              <div id="del" class="icon material-icons">
              <%= link_to project, method: :delete, data: { confirm: 'Soll das Projekt wirklich gelöscht werden?' }, class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored button-middle' do %>
                <i class="material-icons">delete</i>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/projects/index_old.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <h5> Meine Projekte </h5>
    <hr>
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp wide-table" id="test2">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">Projektnummer</th>
          <th class="mdl-data-table__cell--non-numeric">Titel</th>
          <th class="mdl-data-table__cell--non-numeric">Beschreibung</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= project.id %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= project.title %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= project.description %></td>
            <td>
              <%= link_to project, method: :delete, data: { confirm: 'Soll das Projekt wirklich gelöscht werden?' }, class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored button-middle' do %>
                <i class="material-icons">delete</i>
              <% end %>
              <%= link_to project, class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored button-middle' do %>
                <i class="material-icons">folder_open</i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to new_project_path , class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--indigo-500' do %>
      <i class="material-icons">add</i> Neues Projekt
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= render partial: '/shared/header', locals: {project: nil, linkVariable: projects_path, section: 'Neues Projekt'} %>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <h5> Neues Projekt anlegen </h5>
    <hr>
    <%= form_for @project, url: {action: "create"} do |f| %>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input type="text" name="project[title]" id="project_title" class="mdl-textfield__input">
        <label class="mdl-textfield__label" for="project_title">Titel</label>
      </div>
      <br>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input type="text" name="project[description]" id="project_description" class="mdl-textfield__input">
        <label class="mdl-textfield__label" for="project_description">Beschreibung</label>
      </div>
      <br>
      <br>
      <%= f.submit "Erstellen", class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--indigo-500' %>
    <% end %><br>
  </div>
</div>

app/views/projects/show.html.erb
  <header class="mdl-layout__header project-header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
    <span class="mdl-layout-title">
      <%= link_to projects_path , class: 'mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored mdl-color--indigo-500' do %>
      <i class="material-icons">keyboard_arrow_left</i>
      <% end %> <%= @project.title %>
    </span>
    <span class="project-description"><%=truncate(@project.description, :length => 120) %></span>
  </header>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col">
    <!-- Product Breaktdown -->
    <div class="pbs-card">
      <div class="picture_pbs structure mdl-card mdl-shadow--2dp">
        <div class="picture_pbs format mdl-card__title mdl-card--expand">
          <span class="card-title-text">Product Breakdown Structure</span>
        </div>
        <div class="mdl-card__supporting-text">
          Erfassen und editieren Sie die Product Breakdown Structure
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to pbs_path(project: @project), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>Anzeigen <%end%>
        </div>
      </div>
    </div>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="rbs-card">
      <div class="picture_rbs structure mdl-card mdl-shadow--2dp">
        <div class="format mdl-card__title mdl-card--expand">
          <span class="card-title-text">Ressource Breakdown Structure</span>
        </div>
        <div class="mdl-card__supporting-text">
          Erfassen und editieren Sie die Ressource Breakdown Structure
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to rbs_path(project: @project), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>Anzeigen <%end%>
        </div>
      </div>
    </div>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="wbs-card">
      <div class="structure mdl-card mdl-shadow--2dp">
        <div class="format mdl-card__title mdl-card--expand">
          <span class="card-title-text">Work Breakdown Structure</span>
        </div>
        <div class="mdl-card__supporting-text">
          Erfassen und editieren sie die Work Breakdown Structure
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to wbs_path(project: @project), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>Anzeigen <%end%>
        </div>
      </div>
    </div>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="delphi-card">
      <div class="structure mdl-card mdl-shadow--2dp">
        <div class="format mdl-card__title mdl-card--expand">
          <span class="card-title-text">Breitband-Delphi-Methode</span>
        </div>
        <div class="mdl-card__supporting-text">
          Erfassen und editieren Sie die Breitband-Delphi-Methode
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to delphi_index_path(project: @project), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>Anzeigen <%end%>
        </div>
      </div>

    </div>
  </div>

    <div class="mdl-cell mdl-cell--4-col">
      <div class="ram-card">
        <div class="structure mdl-card mdl-shadow--2dp">
          <div class="format mdl-card__title mdl-card--expand">
            <span class="card-title-text">Ressource Allocation Matrix</span>
          </div>
          <div class="mdl-card__supporting-text">
            Vervollständigen der Ressource Allocation Matrix
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <%= link_to ram_index_path(project: @project), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>Anzeigen <%end%>
          </div>

        </div>
      </div>
  </div>
    <div class="mdl-cell mdl-cell--4-col">
    <div class="roadmap-card">
      <div class="structure mdl-card mdl-shadow--2dp">
        <div class="format mdl-card__title mdl-card--expand">
          <span class="card-title-text">Roadmap</span>
        </div>
        <div class="mdl-card__supporting-text">
          Roadmap anzeigen
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to roadmaps_path(project: @project), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>Anzeigen <%end%>
        </div>
      </div>
    </div>
  </div>

</div>
