config/routes.rb
Rails.application.routes.draw do

  get 'roadmap/index'

  devise_for :users
  resources :projects
  resources :rbs, :role, :requirment
  resources :pbs, :subproducts, :moduls, :components
  resources :wbs, :subtask, :workpackage
  resources :delphi, :question, :response
  resources :ram, :allocationitems
  resources :kind, controller: 'rbs'
  resources :task, controller: 'wbs'
  resources :questionaries, controller: 'delphi'
  resources :roadmaps

  root 'projects#index'

end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :modul
  has_one :allocationitem, dependent: :destroy
  validates :name, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :questionary
end

app/models/eventdate.rb
class Eventdate < ActiveRecord::Base
  belongs_to :workpackage
end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :roles, dependent: :destroy
  belongs_to :project
  validates :name, presence: true
end

app/models/modul.rb
class Modul < ActiveRecord::Base
  belongs_to :subproduct
  has_many :components, dependent: :destroy
  validates :name, presence: true
end

app/models/predecessor.rb
class Predecessor < ActiveRecord::Base
  belongs_to :workpackages
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :subproducts, dependent: :destroy
  has_many :kinds, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :questionarys, dependent: :destroy
  has_many :roadmaps, dependent: :destroy
  validates :title, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionary
  belongs_to :workpackage
  has_many :responses
end

app/models/requirment.rb
class Requirment < ActiveRecord::Base
  belongs_to :role

  validates :qualifikation, :experience, presence: true
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :realistic, :optimistic, :pessimistic, presence: true, numericality: { only_integer: true }
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
  belongs_to :project
  belongs_to :questionary

  validates :start, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :kind
  has_one :allocationitem
  has_many :requirments, dependent: :destroy
  validates :name, presence: true
end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
  belongs_to :project
  has_many :moduls, dependent: :destroy
  validates :name, presence: true
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  has_many :workpackages, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subtasks, dependent: :destroy
  belongs_to :project
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :responses, dependent: :destroy
  has_many :userquests, dependent: :destroy
  has_many :questionarys, through: :userquests

  validates_presence_of :first_name, :last_name
end

app/models/userquest.rb
class Userquest < ActiveRecord::Base
  belongs_to :user
  belongs_to :questionary
end

app/controllers/ram_controller.rb
class RamController < ApplicationController



  def index
   @project = Project.find(params[:project])
   @allocationItem = Allocationitem.new
   roles_select
   components_select
  end

  private

    def roles_select
      @roles = Array.new
      @project.kinds.each do |kind|
        kind.roles.each do |role|
          @roles.push(role)
        end
      end
    end

    def components_select
      @components = Array.new
      @project.subproducts.each do |subproduct|
        subproduct.moduls.each do |modul|
          modul.components.each do |component|
            @components.push(component)
          end
        end
      end
    end
end

app/helpers/pbs_helper.rb
module PbsHelper
end

app/helpers/ram_helper.rb
module RamHelper
end

app/helpers/rbs_helper.rb
module RbsHelper
end

app/helpers/wbs_helper.rb
module WbsHelper
end

app/views/ram/index.html.erb
<%= render partial: '/shared/header', locals: {project: @project, linkVariable: @project, section: 'Ressource-Allocation-Matrix'} %>

<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp wide-table" id="test2">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Projekt</th>
      <th class="mdl-data-table__cell--non-numeric">Aufgabe</th>
      <th class="mdl-data-table__cell--non-numeric">Teilaufgabe</th>
      <th class="mdl-data-table__cell--non-numeric">Arbeitspaket</th>
      <th class="mdl-data-table__cell--non-numeric">Einsatzmittel</th>
      <th class="mdl-data-table__cell--non-numeric">Komponente</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr class="first-level">
      <td class="mdl-data-table__cell--non-numeric"><%= @project.title %></td>
      <td class="mdl-data-table__cell--non-numeric"></td>
      <td class="mdl-data-table__cell--non-numeric"></td>
      <td class="mdl-data-table__cell--non-numeric"></td>
      <td class="mdl-data-table__cell--non-numeric"></td>
      <td class="mdl-data-table__cell--non-numeric"></td>
      <td class="mdl-data-table__cell--non-numeric"></td>
    </tr>
      <% @project.tasks.each do |task| %>
        <tr class="second-level">
          <td></td>
          <td class="mdl-data-table__cell--non-numeric">
            <%=task.name %>
          </td>
          <td class="mdl-data-table__cell--non-numeric"></td>
          <td class="mdl-data-table__cell--non-numeric"></td>
          <td class="mdl-data-table__cell--non-numeric"></td>
          <td class="mdl-data-table__cell--non-numeric"></td>
          <td class="mdl-data-table__cell--non-numeric"></td>
        </tr>
        <% task.subtasks.each do |subtask| %>
          <tr class="third-level">
            <td class="mdl-data-table__cell--non-numeric"></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
            <td class="mdl-data-table__cell--non-numeric"><%=subtask.name%></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
            <td class="mdl-data-table__cell--non-numeric"></td>
          </tr>
            <% subtask.workpackages.each do |work| %>
              <tr class="fourth-level">
                <td class="mdl-data-table__cell--non-numeric"></td>
                <td class="mdl-data-table__cell--non-numeric"></td>
                <td class="mdl-data-table__cell--non-numeric"></td>
                <td class="mdl-data-table__cell--non-numeric">
                  <%=work.name%>
                </td>
                <%= form_for @allocationItem, url: {action: "create", controller: 'allocationitems'} do |f| %>
                  <%= f.hidden_field :workpackage_id, value: work.id %>
                  <td class="mdl-data-table__cell--non-numeric">
                    <% if work.allocationitem %>
                      <%= work.allocationitem.role.name %>
                    <% else %>
                      <% unless @components.empty? or @roles.empty? %>
                        <%= f.select(:role_id) do %>
                         <% @roles.each do |c| -%>
                            <%= content_tag(:option, c.name, value: c.id) %>
                          <% end %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                  <td class="mdl-data-table__cell--non-numeric">
                    <% if work.allocationitem %>
                      <%= work.allocationitem.component.name %>
                    <% else %>
                      <% unless @components.empty? or @roles.empty? %>
                        <%= f.select(:component_id) do %>
                         <% @components.each do |c| -%>
                            <%= content_tag(:option, c.name, value: c.id) %>
                          <% end %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                    <% unless @components.empty? or @roles.empty? or work.allocationitem %>
                    <td>
                      <div id="work<%=work.id%>" class="icon material-icons">
                        <%= f.button '', class: 'mdl-button mdl-js-button mdl-button--icon' do %>
                          <i class="material-icons">save</i>
                        <% end %>
                      </div>
                      <div class="mdl-tooltip" for="work<%=work.id%>">
                        Speichern
                      </div>
                    </td>
                    <% end %>
                  <%end%>
                  <% if work.allocationitem %>
                    <td class="button-cell">
                      <div class="icon material-icons">
                        <span class="onMouseOver">
                         <%= button_to allocationitem_path(work.allocationitem, project: @project.id), method: :delete, class: 'mdl-button mdl-js-button mdl-button--icon' do %>
                            <i class="material-icons">delete</i>
                          <% end %>
                        </span>
                      </div>
                    </td>
                  <% end %>
              </tr>
            <%end%>
        <%end%>
    <%end%>
  </tbody>
</table>