config/routes.rb
Rails.application.routes.draw do

  get 'roadmap/index'

  devise_for :users
  resources :projects
  resources :rbs, :role, :requirment
  resources :pbs, :subproducts, :moduls, :components
  resources :wbs, :subtask, :workpackage
  resources :delphi, :question, :response
  resources :ram, :allocationitems
  resources :kind, controller: 'rbs'
  resources :task, controller: 'wbs'
  resources :questionaries, controller: 'delphi'
  resources :roadmaps

  root 'projects#index'

end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :modul
  has_one :allocationitem, dependent: :destroy
  validates :name, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :questionary
end

app/models/eventdate.rb
class Eventdate < ActiveRecord::Base
  belongs_to :workpackage
end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :roles, dependent: :destroy
  belongs_to :project
  validates :name, presence: true
end

app/models/modul.rb
class Modul < ActiveRecord::Base
  belongs_to :subproduct
  has_many :components, dependent: :destroy
  validates :name, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :subproducts, dependent: :destroy
  has_many :kinds, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :questionarys, dependent: :destroy
  has_many :roadmaps, dependent: :destroy
  validates :title, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionary
  belongs_to :workpackage
  has_many :responses
end

app/models/requirment.rb
class Requirment < ActiveRecord::Base
  belongs_to :role

  validates :qualifikation, :experience, presence: true
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :realistic, :optimistic, :pessimistic, presence: true, numericality: { only_integer: true }
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
  belongs_to :project
  belongs_to :questionary

  validates :start, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :kind
  has_one :allocationitem
  has_many :requirments, dependent: :destroy
  validates :name, presence: true
end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
  belongs_to :project
  has_many :moduls, dependent: :destroy
  validates :name, presence: true
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  has_many :workpackages, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subtasks, dependent: :destroy
  belongs_to :project
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :responses, dependent: :destroy
  has_many :userquests, dependent: :destroy
  has_many :questionarys, through: :userquests

  validates_presence_of :first_name, :last_name
end

app/models/userquest.rb
class Userquest < ActiveRecord::Base
  belongs_to :user
  belongs_to :questionary
end

app/helpers/pbs_helper.rb
module PbsHelper
end

app/helpers/ram_helper.rb
module RamHelper
end

app/helpers/rbs_helper.rb
module RbsHelper
end

app/helpers/wbs_helper.rb
module WbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projektmanagement</title>
  <%= javascript_include_tag 'http://www.google.com/jsapi' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">
            <%= link_to projects_path, class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored button-middle' do %>
              <i class="material-icons">home</i>
            <% end %>
            Projektmanagement</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <%= render partial: '/shared/user_widget'%>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
          </nav>
        </div>
      </header>
      <% if user_signed_in? %>
        <div class="mdl-layout__drawer">
          <span class="mdl-layout-title">Projekte</span>
          <nav class="mdl-navigation">
            <% @projects.each do |project| %>
              <%= link_to project, class: 'mdl-navigation__link' do %><%= project.title %><% end %>
            <% end %>
          </nav>
        </div>
      <% end %>
      <main class="mdl-layout__content">
          <div class="mdl-grid mdl-grid--no-spacing">
            <div class="mdl-cell mdl-cell--12-col page-layout">
              <%= yield %>
            </div>
          </div>
      </main>
    </div>
  </body>
</html>

app/views/shared/_flash_message.erb
<% if flash[:success] %>
  <div class="success"><%= flash[:success] %></div>
<% end %>
<% if flash[:danger] %>
  <div class="danger"><%= flash[:danger] %></div>
<% end %>

app/views/shared/_header.html.erb
<header class="mdl-layout__header project-header">
  <div class="mdl-layout__header-row">
    <!-- Title -->
  <span class="mdl-layout-title">
    <%= link_to linkVariable , class: 'mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored mdl-color--indigo-500' do %>
    <i class="material-icons">keyboard_arrow_left</i>
    <% end %>
    <%= @project.title %>
  </span>
  <span class="header-chevron"><i class="material-icons">chevron_right</i></span>
  <span class="project-description"><%= section %></span>
</header>
<%= render partial: '/shared/flash_message'%>

app/views/shared/_header_without_projecttitle.html.erb
<header class="mdl-layout__header project-header">
  <div class="mdl-layout__header-row">
    <!-- Title -->
  <span class="mdl-layout-title">
    <%= link_to linkVariable , class: 'mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored mdl-color--indigo-500' do %>
    <i class="material-icons">keyboard_arrow_left</i>
    <% end %>
  </span>
  <span class="header-chevron"><i class="material-icons">chevron_right</i></span>
  <span class="project-description"><%= section %></span>
</header>
<%= render partial: '/shared/flash_message'%>

app/views/shared/_user_widget.erb
<% if user_signed_in? %>
  Eingeloggt als &nbsp;<strong><%= current_user.first_name %> <%= current_user.last_name %></strong>
  <button id="demo-menu-lower-right"
          class="mdl-button mdl-js-button mdl-button--icon">
    <i class="material-icons">keyboard_arrow_down</i>
  </button>
  <% if quest_count == 0 %>
    <i class="material-icons" style="color: #BDBDBD;">live_help</i>
  <% else %>
    <span class="material-icons mdl-badge" data-badge="<%= quest_count %>" id="user-badge">live_help</span>
  <% end %>
<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
    for="demo-menu-lower-right">
  <%= link_to edit_user_registration_path do%>
  <li class="mdl-menu__item">Profil bearbeiten</li>
  <%end%>
  <%= link_to destroy_user_session_path, method: :delete do%>
    <li class="mdl-menu__item">Logout</li>
  <% end %>
</ul>

<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
    for="user-badge">
  <% current_user.userquests.each do |uquest| %>
    <% if uquest.newquest == true %>
    <%= link_to response_index_path(uquest.questionary, project: uquest.questionary.project,questionary: uquest.questionary) do %>
      <li class="mdl-menu__item"><%= uquest.questionary.project.title %> > Runde <%=uquest.questionary.runde%></li>
      <% end %>
    <% end %>
  <% end %>
</ul>

<% else %>
  Nicht eingeloggt!&nbsp;
  <%= link_to new_user_registration_path do %>
    <strong>Registrieren</strong>
  <% end %>
  &nbsp;oder&nbsp;
  <%= link_to new_user_session_path do %>
    <strong >Login</strong>
  <% end %>
<% end %>